### ISSUE TITLE
Additional Decimal Point in Rate Constant

### ISSUE THREAD

**Issue by simonom** [wacl-york/mcm-web#240]
Just a quick one. When downloading the APINENE and CH4 scheme (including inorganic reactions) today (18/12/2023), equation number 328 has an additional decimal point in the rate constant:

 {328 } C614NO3 + OH = C614CO + NO2 : 7.1.11E-12 ;

I don't know what the correct rate constant is for this reaction, but in previous downloads the same reaction read:
 
C614NO3 + OH = C614CO + NO2 : 71.11D-12 ;

Thanks,
Simon

**Comment by stulacy** [comment]
Ah sorry about that! I'll take a look tomorrow if that's ok. Did you notice any other affected reactions?

**Comment by simonom** [comment]
Nope. And, if there were a similar issue with this subset, then the programme I used would have returned an error. (I've only tried the APINENE with CH4 scheme)

**Comment by stulacy** [comment]
I've fixed this issue which was also affecting another reaction:

`C729CHO + NO3 = C729CO3 + HNO3 : KNO3AL*1.7.0 ; ` (should be 17.0)

I'll close this issue now but please reopen it if you see another bug.
