### ISSUE TITLE
xml file not available

### ISSUE THREAD

**Issue by simonom** [wacl-york/mcm-web#243]
Hiya,

Bigger issue this time.

On the previous MCM website, there was ability to download the xml file (containing SMILES strings) for a chemical system. But I do not see this feature on the updated website. It is very useful for converting MCM identifiers for species into molecular formulas. 

Are there plans to provide xml downloads on the new website?

Thanks,
Simon

**Comment by stulacy** [comment]
Hi Simon, there aren't any current plans for adding the XML export back in as we were under the impression that this functionality wasn't being used that often.
Someone else has requested the old "molecular weights" export which we're currently looking into (#248). This is a TSV file containing the Smiles, Inchi, and mass for every species in the selected mechanism. 

Would this fit your needs, or do you need the additional information provided by the XML (RO2 species, reaction definitions), and/or the XML format itself?
Cheers, and happy new year! Stu

**Comment by simonom** [comment]
Thanks Stu,

The TSV file sounds spot on for what I need, which is the SMILES and the associated MCM name of each species. It will possibly save space, since I wasn’t using the additional information in the XML, such as reaction definitions. Therefore, please close #243 and I look forward to resolution of #248.

Kind regards,
Simon O'Meara (He/Him)

National Centre for Atmospheric Science Postdoctoral Research Associate

**Comment by stulacy** [comment]
Thanks Simon, moving discussion to #248
