### ISSUE TITLE
Incorrect InChI for CH3SO2

### ISSUE THREAD

**Issue by RolfSander** [wacl-york/mcm-web#265]
It seems that the InChI for `CH3SO2`
(https://mcm.york.ac.uk/MCM/species/CH3SO2) is incorrect. It should have
3 H atoms, not 4. The correct InChI is probably
`InChI=1S/CH3O2S/c1-4(2)3/h1H3`, see:
https://commonchemistry.cas.org/detail?cas_rn=4853-80-9

ps: Finding this was only possible with the new KPP export function. Thanks again :-)

**Comment by stulacy** [comment]
Sorry for the (very) delayed response to this. We discussed this internally briefly but it got lost in the discussion about adding Inchis for inorganic compounds at the same time. I'll pick it back up and try to finalise it shortly.

**Comment by stulacy** [comment]
The InChI has now been updated, thanks for pointing this out.
