### ISSUE TITLE
Titles of MCM web pages

### ISSUE THREAD

**Issue by RolfSander** [wacl-york/mcm-web#321]
Hello, I have a feature request for the new MCM webpages: I often have
several MCM web pages opened in the tabs of my browser. Unfortunately,
they all have the same title, simply `MCM`. This makes it difficult to
find the right tab when comparing different species. For the web pages
of individual MCM species, I suggest to add the name of the species to
the title. For example, the html code of the isoprene (`C5H8`) page could be:

```
<title>MCM - C5H8</title>
```

**Comment by stulacy** [comment]
Sorry Rolf, I didn't receive a notification for this. I'll look into this shortly as it is a useful suggestion.

**Comment by RolfSander** [comment]
Thanks!

(Sorry about not being notified. Next time I can mention you directly when I open a new issue...)

**Comment by stulacy** [comment]
No worries at all, somehow I didn't have my notifications setup for all repo events. I've corrected it now.

**Comment by RolfSander** [comment]
There is also another issue which I opened a while ago which doesn't have a reply yet:
https://github.com/wacl-york/mcm-web/issues/265

I'm not sure though who would be the right person to look at this.

**Comment by stulacy** [comment]
This is now live, thanks for the suggestion.

**Comment by RolfSander** [comment]
Great, thanks @stulacy  !
